# Giving it a name
name: Build succeeds on PR

# when to run the workflow
on:
  pull_request:
    branches:
      - master

# jobs to run
jobs:
    buid:
        name: Build on the latest ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              run: node --version
            - uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm install
            
            - name: Build
              run: npm run build